# Placeholder for internal Python library.

package(
    default_visibility = [
        "//tensorflow_recommenders:__subpackages__",
    ],
)

licenses(["notice"])

py_library(
    name = "experimental",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders/experimental/models",
        "//tensorflow_recommenders/experimental/optimizers",
    ],
)
