# Placeholder for internal Python library.

# TensorFlow Recommenders, a TensorFlow library for building recommender systems.
package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

py_library(
    name = "tensorflow_recommenders",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders/datasets",
        "//tensorflow_recommenders/examples",
        "//tensorflow_recommenders/layers",
        "//tensorflow_recommenders/losses",
        "//tensorflow_recommenders/metrics",
        "//tensorflow_recommenders/models",
        "//tensorflow_recommenders/tasks",
    ],
)
